# Этап сборки
FROM golang:1.24-alpine AS builder
RUN apk update && apk add make
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o app ./cmd/app/main.go


# Этап создания конечного образа
FROM scratch
WORKDIR /app
COPY --from=builder /app/app .
COPY --from=builder /app/db/sqlite ./db/sqlite
CMD ["./app"]
