# Этап сборки
FROM golang:1.24-bookworm AS builder
RUN apt update && apt install make
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o app ./cmd/app/main.go


# Этап создания конечного образа
FROM alpine:3.21
USER nobody:nobody
WORKDIR /app/
COPY --from=builder /app/app .
COPY --from=builder /app/db/sqlite .
CMD ["./app"]
