# Этап сборки
FROM golang:1.24-alpine AS builder
RUN apk update && apk add make
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN make build


# Этап создания конечного образа
FROM gcr.io/distroless/static-debian12
COPY --from=build /etc/passwd /etc/passwd
USER nobody:nobody
WORKDIR /app/
COPY --from=builder /app/app .
CMD ["./app"]
