FROM golang:1.24-alpine

WORKDIR /app
RUN mkdir -p db/sqlite

RUN apk update --no-cache && \
    apk add git make && \
    go install github.com/air-verse/air@v1.61.7 && \
    go install github.com/go-delve/delve/cmd/dlv@v1.24.2

CMD ["air", "-c", ".air_debug.toml", "--"]
