FROM golang:1.24-alpine

WORKDIR /app
RUN mkdir -p db/sqlite

RUN apk update --no-cache && \
    apk add git make && \
    go install github.com/air-verse/air@v1.61.7

CMD ["air", "-c", ".air.toml", "--"]
