# Этап сборки
FROM golang:1.24-alpine AS builder
RUN apk update --no-cache && \
    apk add make
WORKDIR /app
RUN mkdir -p db/sqlite
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN make build


# Этап создания конечного образа
FROM alpine:3.21
USER nobody:nobody
WORKDIR /app
COPY --from=builder --chown=nobody /app/build/app .
COPY --from=builder --chown=nobody /app/db/sqlite ./db/sqlite
CMD ["./app"]
